connector.name=kafka
# Указываем имя топика, который хотим читать как таблицу
kafka.table-names=my_topic
# Адрес брокера внутри Docker-сети (имя сервиса из docker-compose)
kafka.nodes=kafka-broker:9092
kafka.hide-internal-columns=false